server:
  port: 8080
  servlet:
    session:
      # 设置session的有效期为5分钟
      timeout: 5m
    compression:
      # 开启返回结果压缩
      enabled: true
      min-response-size: 2KB


spring:
  config:
    import: application-dal.yaml,application-web.yaml,application-config.yaml,application-image.yaml,application-email.yaml,application-rabbitmq.yaml,application-ai.yaml

  main:
    # 引入下面这个配置，主要是为了解决自定义实现的多数据源功能，自主注册的datasource替换默认的
    allow-bean-definition-overriding: true
    # 允许循环引用
    allow-circular-references: true

  mvc:
    async:
      request-timeout:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 使用liquibase管理数据库表变更
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB



servlet:
  tomcat:
    # 解决上传图片超过2MB之后，出现连接重置的问题, -1: 表示不限制请求体的大小。
    # 在生产环境中，建议设置一个合理的最大值
    max-swallow-size: -1



database:
  name: code_community


# mybatis 相关统一配置
mybatis-plus:
  configuration:
    #开启下划线转驼峰
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto



#logging:
#  level:
#    com.levent.service.rank.service.impl.*: debug # 指定具体包下的日志输出级别


knife4j:
  enable: true
  setting:
    language: zh_CN
  openapi:
    title: 码客社区
    description: 致力于技术分享的社区
    version: 1.0
    concat:
     - levent
    email: 1993262229@qq.com
    group:
      admin:
        group-name: 后台接口分组
        api-rule: package
        api-rule-resources:
          - com.levent.web.admin
      front:
        group-name: 前台接口分组
        api-rule: package
        api-rule-resources:
          - com.levent.web.front



