#邮箱配置
spring:
  mail:
    host: smtp.qq.com
    from: guan.levent@foxmail.com
    username: guan.levent
    password: ptagwqbyeqjlhiaj
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          starttls:
            enable: true
            required: true

alarm:
  # 接收报警的用户邮箱，多个人时，使用英文逗号分隔
  user: guan.levent@foxmail.com