spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zkzc0722@Gxy
  dynamic:
#    primary: master
    datasource:
      master:
        url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: zkzc0722@Gxy
      filters: stat
      initialSize: 0
      minIdle: 1
      maxActive: 200
      maxWait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 200000
      testWhileIdle: true
      testOnBorrow: true
      validationQuery: select 1
      slave:
        url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: xinyi
        password: 123456
  redis:
    host: 172.28.64.1
    port: 6379
    password: